# Generated by Django 4.2.21 on 2025-08-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='capacity',
            field=models.IntegerField(blank=True, help_text='Maximum number of people the facility can accommodate', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Whether this facility is featured on the platform'),
        ),
        migrations.AddField(
            model_name='facility',
            name='membership_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual membership fee', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='membership_required',
            field=models.BooleanField(default=False, help_text='Whether membership is required to use the facility'),
        ),
        migrations.AddField(
            model_name='facility',
            name='parking_spaces',
            field=models.IntegerField(blank=True, help_text='Number of parking spaces available', null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='year_established',
            field=models.IntegerField(blank=True, help_text='Year the facility was established', null=True),
        ),
    ]
