# Generated by Django 4.2.21 on 2025-08-11 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courts', '0002_facility_capacity_facility_is_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='court',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='court',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='court',
            name='pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='court',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_recurring',
            field=models.BooleanField(default=True, help_text='Whether this time slot repeats daily'),
        ),
        migrations.CreateModel(
            name='CourtPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='court_photos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='courts.court')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
    ]
