# Generated by Django 4.2.21 on 2025-08-11 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('player', 'Player'), ('owner', 'Court Owner'), ('admin', 'Admin')], default='player', max_length=10),
        ),
    ]
